### ISSUE TITLE
Creating group dimensions in version 1.7.1 fails with "'Group' object has no attribute '_format'"

### ISSUE THREAD

**Issue by scottstanie** [h5netcdf/h5netcdf#293]
#### What happened:

(Continuing from https://github.com/h5netcdf/h5netcdf/pull/292#issuecomment-3412823743)

```python-traceback
File ~/.cache/uv/archive-v0/B-uL3YDLPCiDhjNU19kol/lib/python3.12/site-packages/h5netcdf/core.py:1033, in Group.dimensions(self, value)
   1031 @dimensions.setter
   1032 def dimensions(self, value):
-> 1033     if self._format == "NETCDF4_CLASSIC":
   1034         unlimited_dims = list(filter(lambda s: s in [None, 0], value.values()))
   1035         if len(unlimited_dims) > 1:

AttributeError: 'Group' object has no attribute '_format'
```

#### What you expected to happen:

This code worked with h5netcdf versions < 1.7

#### MCVE Code Sample

```bash
uv run --with ipython,h5netcdf==1.7.1,numpy ipython
```

```python
import h5netcdf
print(h5netcdf.__version__)
# 1.7.1

f = h5netcdf.File("test1.nc", mode="a")
group = f.create_group("data")
y, x = np.arange(3), np.arange(3)
dims = {'y': y.size, 'x': x.size}
group.dimensions = dims
```

#### Expected Output

A group created successfully

#### Version

Version 1.7.1 installed via pip/uv

<details><summary>Output of <tt>print(h5py.version.info, f"\nh5netcdf {h5netcdf.__version__}")</tt></summary>

```
Summary of the h5py configuration
---------------------------------

h5py    3.15.1
HDF5    1.14.6
Python  3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 15:57:01) [Clang 17.0.6 ]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   2.3.4
cython (built with) 3.1.4
numpy (built against) 2.3.4
HDF5 (built against) 1.14.6

h5netcdf 1.7.1
```

</details>

**Comment by kmuehlbauer** [comment]
Thanks @scottstanie  for the report and the reproducer. This looks like another regression of the NETCDF4_CLASSIC implementation.

**Comment by hmaarrfk** [comment]
did this work with 1.7.0?
